version: '3'
services:
  frontend:
    build:
      context: ./frontend   # 리액트 앱의 경로
      dockerfile: Dockerfile-frontend
    restart: unless-stopped
    ports:
      - "80:80"         # 리액트 앱 포트 매핑
    volumes:
      - ./frontend:/app     # 로컬 디렉토리를 컨테이너에 마운트하여 실시간 코드 변경 반영 (개발용)
    depends_on:
      - backend             # 백엔드 서비스가 먼저 시작되어야 함
    image: react-test-app_frontend:latest

  backend:
    build:
      context: ./backend    # 스프링 앱의 경로
      dockerfile: Dockerfile-backend
    restart: unless-stopped
    ports:
      - "8080:8080"         # 스프링 앱 포트 매핑
    volumes:
      - ./backend:/app      # 로컬 디렉토리를 컨테이너에 마운트하여 실시간 코드 변경 반영 (개발용)
    image: react-test-app_backend:latest

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile-jenkins
    restart: unless-stopped
    user: jenkins
    ports:
      - "8888:2024"
    volumes:
      - /home/jenkins/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=2024
    image: react-test-app_jenkins:latest
    